Repository InfinitiBit/graphbit, pull requests merged in 2025-09, with the labels that each got.

#189 [Refactor] docs: update root README.md with new links and installation instructions
  README.md
Labels: refactor

#191 [Feature] docs: update contributor list and fix image path in README
  .github/workflows/update-contributors.yml
  README.md
  docs/index.md
Labels: enhancement

#193 [Documentation]: simplify header and enhance visual elements in index.md
  docs/index.md
Labels: documentation

#195 [Bugfix] update extra.css
  docs/stylesheets/extra.css
Labels: bug

#196 [Documentation] GraphBit Framework License document
  LICENSE.md
Labels: documentation

#197 [Refactor] remove unused configuration files of pre commit hook
  .cz.toml
  .hadolint.yaml
Labels: refactor

#200 [Documentation] Root README update.
  README.md
Labels: documentation

#207 [Feature] Anthropic tool calling support
  README.md
  core/src/llm/anthropic.rs
  core/src/llm/providers.rs
  core/src/workflow.rs
Labels: enhancement

#219 [feature] Fireworks AI integration.
  core/src/llm/fireworks.rs
  core/src/llm/mod.rs
  core/src/llm/providers.rs
  docs/user-guide/concepts.md
  docs/user-guide/llm-providers.md
  python/README.md
  python/src/llm/client.rs
  python/src/llm/config.rs
  tests/python_integration_tests/tests_llm.py
  tests/rust_integration_tests/llm_tests.rs
  tests/rust_unit_tests/llm_provider_tests.rs
Labels: enhancement

#221 [Refactor] remove reduntant worflow test from core
  core/src/workflow_tests.rs
Labels: invalid

#226 [Documentation] update contact email in about.md
  docs/about.md
Labels: documentation

#228 [Feature] Replicate ai provider
  README.md
  core/src/llm/mod.rs
  core/src/llm/providers.rs
  core/src/llm/replicate.rs
  docs/user-guide/llm-providers.md
  docs/user-guide/tool-calling.md
  python/src/llm/config.rs
  tests/python_unit_tests/tests_replicate_provider.py
  tests/rust_unit_tests/llm_provider_tests.rs
Labels: Feature

#231 [Feature] Research paper summarizer agent.
  examples/research-paper-summarizer-agent/README.md
  examples/research-paper-summarizer-agent/backend/constant.py
  examples/research-paper-summarizer-agent/backend/faiss_store.py
  examples/research-paper-summarizer-agent/backend/main-server.py
  examples/research-paper-summarizer-agent/backend/paper_manager.py
  examples/research-paper-summarizer-agent/backend/summarizer.py
  examples/research-paper-summarizer-agent/backend/utils/caching.py
  examples/research-paper-summarizer-agent/frontend/app.py
  examples/research-paper-summarizer-agent/pyproject.toml
Labels: enhancement, Feature

#238 fixed test failures
  core/src/llm/azure_openai.rs
  pyproject.toml
  tests/python_integration_tests/tests_document_loader.py
  tests/python_integration_tests/tests_llm.py
  tests/python_unit_tests/tests_llm_clients.py
  tests/rust_integration_tests/azure_openai_integration_tests.rs
  tests/rust_integration_tests/concurrency_tests.rs
  tests/rust_unit_tests/llm_tests.rs
  tests/rust_unit_tests/workflow_tests.rs
Labels: enhancement, Test

#241 Feature/llmusage
  Cargo.toml
  core/src/llm/azure_openai.rs
  python/Cargo.toml
  python/README.md
  python/src/lib.rs
  python/src/llm/client.rs
  python/src/llm/mod.rs
  python/src/llm/response.rs
  tests/python_integration_tests/tests_llm.py
Labels: enhancement
